name: neurovive
description: "An AI solution that early diagnosis Parkinson disease."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.5.0+5

environment:
  sdk: ^3.9.2

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  shared_preferences:
  go_router:
  flutter_riverpod:
  intl: any
  auto_size_text: ^3.0.0
  riverpod_lint: ^3.0.3
  # Audio recording + file path
  record: ^6.1.2
  path_provider: ^2.1.2 #todo: this doesnt support web so search for something else
  http: ^1.6.0
  rename_app: ^1.6.5

  opencv_dart: ^2.2.1+1
  camera:
  image: ^4.0.17
  image_picker: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0

flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/images/

  fonts:
    - family: Neurovive #the icons
      fonts:
        - asset: fonts/Neurovive.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-VariableFont_wdth,wght.ttf