/// Flutter icons Neurovive
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Neurovive
///      fonts:
///       - asset: fonts/Neurovive.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Neurovive {
  Neurovive._();

  static const _kFontFam = 'Neurovive';
  static const String? _kFontPkg = null;

  static const IconData mic = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retry = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
